/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author Lenovo
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Glavna forma");
        prikaziDatum();
        prikaziVreme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jLabelPozdrav = new javax.swing.JLabel();
        jButtonKreirajUgovorONajmu = new javax.swing.JButton();
        jButtonIzmeniUgovorONajmu = new javax.swing.JButton();
        jLabelDatum = new javax.swing.JLabel();
        jLabelDatumTekst = new javax.swing.JLabel();
        jLabelVremeTekst = new javax.swing.JLabel();
        jLabelVreme = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuZakupac = new javax.swing.JMenu();
        jMenuItemKreirajZakupca = new javax.swing.JMenuItem();
        jMenuItemPregledZakupaca = new javax.swing.JMenuItem();
        jMenuEvidencijaNajma = new javax.swing.JMenu();
        jMenuItemPregledNajma = new javax.swing.JMenuItem();
        jMenuOsiguranje = new javax.swing.JMenu();
        jMenuItemUbaciOsiguranje = new javax.swing.JMenuItem();
        jMenuOprema = new javax.swing.JMenu();
        jMenuItemUbaciOpremu = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelPozdrav.setText("Zdravo, ");

        jButtonKreirajUgovorONajmu.setText("Kreiraj ugovor o najmu");
        jButtonKreirajUgovorONajmu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajUgovorONajmuActionPerformed(evt);
            }
        });

        jButtonIzmeniUgovorONajmu.setText("Izmeni ugovor o najmu");
        jButtonIzmeniUgovorONajmu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniUgovorONajmuActionPerformed(evt);
            }
        });

        jLabelDatumTekst.setText("Datum:");

        jLabelVremeTekst.setText("Vreme:");

        jMenuZakupac.setText("Zakupac");

        jMenuItemKreirajZakupca.setText("Kreiraj");
        jMenuItemKreirajZakupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajZakupcaActionPerformed(evt);
            }
        });
        jMenuZakupac.add(jMenuItemKreirajZakupca);

        jMenuItemPregledZakupaca.setText("Pregled");
        jMenuItemPregledZakupaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledZakupacaActionPerformed(evt);
            }
        });
        jMenuZakupac.add(jMenuItemPregledZakupaca);

        jMenuBar1.add(jMenuZakupac);

        jMenuEvidencijaNajma.setText("Ugovor o najmu");

        jMenuItemPregledNajma.setText("Pregled");
        jMenuItemPregledNajma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledNajmaActionPerformed(evt);
            }
        });
        jMenuEvidencijaNajma.add(jMenuItemPregledNajma);

        jMenuBar1.add(jMenuEvidencijaNajma);

        jMenuOsiguranje.setText("Brend");

        jMenuItemUbaciOsiguranje.setText("Ubaci");
        jMenuItemUbaciOsiguranje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUbaciOsiguranjeActionPerformed(evt);
            }
        });
        jMenuOsiguranje.add(jMenuItemUbaciOsiguranje);

        jMenuBar1.add(jMenuOsiguranje);

        jMenuOprema.setText("Oprema");

        jMenuItemUbaciOpremu.setText("Ubaci");
        jMenuItemUbaciOpremu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUbaciOpremuActionPerformed(evt);
            }
        });
        jMenuOprema.add(jMenuItemUbaciOpremu);

        jMenuBar1.add(jMenuOprema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVremeTekst)
                            .addComponent(jLabelDatumTekst, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonIzmeniUgovorONajmu))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPozdrav, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(jButtonKreirajUgovorONajmu)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelPozdrav))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonKreirajUgovorONajmu, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButtonIzmeniUgovorONajmu, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDatumTekst, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelVreme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelVremeTekst))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemKreirajZakupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajZakupcaActionPerformed
        koordinator.Koordinator.getInstance().otvoriDodajZakupcaFormu();
    }//GEN-LAST:event_jMenuItemKreirajZakupcaActionPerformed

    private void jMenuItemUbaciOsiguranjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUbaciOsiguranjeActionPerformed
        koordinator.Koordinator.getInstance().otvoriDodajBrendFormu();
    }//GEN-LAST:event_jMenuItemUbaciOsiguranjeActionPerformed

    private void jMenuItemUbaciOpremuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUbaciOpremuActionPerformed
        koordinator.Koordinator.getInstance().otvoriDodajOpremuForma();
    }//GEN-LAST:event_jMenuItemUbaciOpremuActionPerformed

    private void jMenuItemPregledZakupacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledZakupacaActionPerformed
        try{
            koordinator.Koordinator.getInstance().otvoriPrikazZakupaca();
        }catch(Exception ex){
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemPregledZakupacaActionPerformed

    private void jButtonKreirajUgovorONajmuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajUgovorONajmuActionPerformed
        try {
            koordinator.Koordinator.getInstance().otvoriKreirajUgovorONajmu();
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonKreirajUgovorONajmuActionPerformed

    private void jButtonIzmeniUgovorONajmuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniUgovorONajmuActionPerformed
        try {
            koordinator.Koordinator.getInstance().otvoriIzmeniUgovorONajmu();
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonIzmeniUgovorONajmuActionPerformed

    private void jMenuItemPregledNajmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledNajmaActionPerformed
        try {
            koordinator.Koordinator.getInstance().otvoriPrikazUgovorONajmuFormu();
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemPregledNajmaActionPerformed

    /**
     * @param args the command line arguments
     */

    public JLabel getjLabelPozdrav() {
        return jLabelPozdrav;
    }

    /**
     * @param args the command line arguments
     */
    public void setjLabelPozdrav(JLabel jLabelPozdrav) {
        this.jLabelPozdrav = jLabelPozdrav;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmeniUgovorONajmu;
    private javax.swing.JButton jButtonKreirajUgovorONajmu;
    private javax.swing.JLabel jLabelDatum;
    private javax.swing.JLabel jLabelDatumTekst;
    private javax.swing.JLabel jLabelPozdrav;
    private javax.swing.JLabel jLabelVreme;
    private javax.swing.JLabel jLabelVremeTekst;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEvidencijaNajma;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemKreirajZakupca;
    private javax.swing.JMenuItem jMenuItemPregledNajma;
    private javax.swing.JMenuItem jMenuItemPregledZakupaca;
    private javax.swing.JMenuItem jMenuItemUbaciOpremu;
    private javax.swing.JMenuItem jMenuItemUbaciOsiguranje;
    private javax.swing.JMenu jMenuOprema;
    private javax.swing.JMenu jMenuOsiguranje;
    private javax.swing.JMenu jMenuZakupac;
    // End of variables declaration//GEN-END:variables

    private void prikaziDatum() {
        Timer timer = new Timer(1000, e -> {
            String datum = new SimpleDateFormat("dd.MM.yyyy").format(new Date());
            jLabelDatum.setText(datum);
        });
        timer.start();
    }

    private void prikaziVreme() {
        Timer timer = new Timer(1000, e -> {
            String vreme = new SimpleDateFormat("HH.mm.ss").format(new Date());
            jLabelVreme.setText(vreme);
        });
        timer.start();
    }
}
