/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forme;

import java.awt.Cursor;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo
 */
public class LoginForma extends javax.swing.JPanel {

    /**
     * Creates new form LoginForma1
     */
    public LoginForma() {
        initComponents();
        jButtonLOGIN.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButtonIzadji.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    public JButton getjButtonIzadji() {
        return jButtonIzadji;
    }

    public void setjButtonIzadji(JButton jButtonIzadji) {
        this.jButtonIzadji = jButtonIzadji;
    }

    public JButton getjButtonLOGIN() {
        return jButtonLOGIN;
    }

    public void setjButtonLOGIN(JButton jButtonLOGIN) {
        this.jButtonLOGIN = jButtonLOGIN;
    }

    public JPasswordField getjPasswordField() {
        return jPasswordField;
    }

    public void setjPasswordField(JPasswordField jPasswordField) {
        this.jPasswordField = jPasswordField;
    }

    public JTextField getjTextFieldKorIme() {
        return jTextFieldKorIme;
    }

    public void setjTextFieldKorIme(JTextField jTextFieldKorIme) {
        this.jTextFieldKorIme = jTextFieldKorIme;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIzadji = new javax.swing.JButton();
        jButtonLOGIN = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jTextFieldKorIme = new javax.swing.JTextField();
        jLabelKorIme = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();

        jButtonIzadji.setText("Izadji");
        jButtonIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzadjiActionPerformed(evt);
            }
        });

        jButtonLOGIN.setText("Prijavi se");
        jButtonLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLOGINActionPerformed(evt);
            }
        });

        jLabelKorIme.setText("Korisnicko ime:");

        jLabelPass.setText("Lozinka:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonIzadji)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLOGIN))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPass)
                            .addComponent(jLabelKorIme))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField)
                            .addComponent(jTextFieldKorIme, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKorIme)
                    .addComponent(jTextFieldKorIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPass)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLOGIN)
                    .addComponent(jButtonIzadji))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzadjiActionPerformed
        this.getTopLevelAncestor().setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jButtonIzadjiActionPerformed

    private void jButtonLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLOGINActionPerformed

    }//GEN-LAST:event_jButtonLOGINActionPerformed

    public JLabel getjLabelKorIme() {
        return jLabelKorIme;
    }

    public void setjLabelKorIme(JLabel jLabelKorIme) {
        this.jLabelKorIme = jLabelKorIme;
    }

    public JLabel getjLabelPass() {
        return jLabelPass;
    }

    public void setjLabelPass(JLabel jLabelPass) {
        this.jLabelPass = jLabelPass;
    }
    
    public void loginAddActionListener(ActionListener actionListener){
        jButtonLOGIN.addActionListener(actionListener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzadji;
    private javax.swing.JButton jButtonLOGIN;
    private javax.swing.JLabel jLabelKorIme;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldKorIme;
    // End of variables declaration//GEN-END:variables
}
