/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domain.KategorijaOpreme;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo
 */
public class UbaciOpremuForma extends javax.swing.JFrame {

    /**
     * Creates new form DodajOpremuForma
     */
    public UbaciOpremuForma() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelProizvodjac = new javax.swing.JLabel();
        jLabelProizvod = new javax.swing.JLabel();
        jLabelKategorijaOpreme = new javax.swing.JLabel();
        jLabelCenaPoDanu = new javax.swing.JLabel();
        jLabelUkupnaKol = new javax.swing.JLabel();
        jLabelDostupnaKol = new javax.swing.JLabel();
        jButtonDodaj = new javax.swing.JButton();
        jTextFieldProizvodjac = new javax.swing.JTextField();
        jTextFieldProizvod = new javax.swing.JTextField();
        jTextFieldUkupnaKol = new javax.swing.JTextField();
        jTextFieldDostupnaKol = new javax.swing.JTextField();
        jTextFieldCenaPoDanu = new javax.swing.JTextField();
        jComboBoxKategorijaOpreme = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelProizvodjac.setText("Naziv proizvodjaca:");

        jLabelProizvod.setText("Naziv proizvoda:");

        jLabelKategorijaOpreme.setText("Kategorija opreme:");

        jLabelCenaPoDanu.setText("Cena po danu:");

        jLabelUkupnaKol.setText("Ukupna kolicina:");

        jLabelDostupnaKol.setText("Dostupna kolicina:");

        jButtonDodaj.setText("Dodaj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCenaPoDanu, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(jTextFieldCenaPoDanu, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelUkupnaKol, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldUkupnaKol, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKategorijaOpreme, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldProizvod, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jComboBoxKategorijaOpreme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelDostupnaKol, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDodaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDostupnaKol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProizvodjac)
                    .addComponent(jTextFieldProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProizvod)
                    .addComponent(jTextFieldProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKategorijaOpreme)
                    .addComponent(jComboBoxKategorijaOpreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCenaPoDanu)
                    .addComponent(jTextFieldCenaPoDanu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUkupnaKol)
                    .addComponent(jTextFieldUkupnaKol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDostupnaKol)
                    .addComponent(jTextFieldDostupnaKol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonDodaj)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void dodajAddActionListener(ActionListener actionListener){
        jButtonDodaj.addActionListener(actionListener);
    }
    public JButton getjButtonDodaj() {
        return jButtonDodaj;
    }

    public void setjButtonDodaj(JButton jButtonDodaj) {
        this.jButtonDodaj = jButtonDodaj;
    }

    public JComboBox<KategorijaOpreme> getjComboBoxKategorijaOpreme() {
        return jComboBoxKategorijaOpreme;
    }

    public void setjComboBoxKategorijaOpreme(JComboBox<KategorijaOpreme> jComboBoxKategorijaOpreme) {
        this.jComboBoxKategorijaOpreme = jComboBoxKategorijaOpreme;
    }

    public JLabel getjLabelCenaPoDanu() {
        return jLabelCenaPoDanu;
    }

    public void setjLabelCenaPoDanu(JLabel jLabelCenaPoDanu) {
        this.jLabelCenaPoDanu = jLabelCenaPoDanu;
    }

    public JLabel getjLabelDostupnaKol() {
        return jLabelDostupnaKol;
    }

    public void setjLabelDostupnaKol(JLabel jLabelDostupnaKol) {
        this.jLabelDostupnaKol = jLabelDostupnaKol;
    }

    public JLabel getjLabelKategorijaOpreme() {
        return jLabelKategorijaOpreme;
    }

    public void setjLabelKategorijaOpreme(JLabel jLabelKategorijaOpreme) {
        this.jLabelKategorijaOpreme = jLabelKategorijaOpreme;
    }

    public JLabel getjLabelProizvod() {
        return jLabelProizvod;
    }

    public void setjLabelProizvod(JLabel jLabelProizvod) {
        this.jLabelProizvod = jLabelProizvod;
    }

    public JLabel getjLabelProizvodjac() {
        return jLabelProizvodjac;
    }

    public void setjLabelProizvodjac(JLabel jLabelProizvodjac) {
        this.jLabelProizvodjac = jLabelProizvodjac;
    }

    public JLabel getjLabelUkupnaKol() {
        return jLabelUkupnaKol;
    }

    public void setjLabelUkupnaKol(JLabel jLabelUkupnaKol) {
        this.jLabelUkupnaKol = jLabelUkupnaKol;
    }

    public JTextField getjTextFieldCenaPoDanu() {
        return jTextFieldCenaPoDanu;
    }

    public void setjTextFieldCenaPoDanu(JTextField jTextFieldCenaPoDanu) {
        this.jTextFieldCenaPoDanu = jTextFieldCenaPoDanu;
    }

    public JTextField getjTextFieldDostupnaKol() {
        return jTextFieldDostupnaKol;
    }

    public void setjTextFieldDostupnaKol(JTextField jTextFieldDostupnaKol) {
        this.jTextFieldDostupnaKol = jTextFieldDostupnaKol;
    }

    public JTextField getjTextFieldProizvod() {
        return jTextFieldProizvod;
    }

    public void setjTextFieldProizvod(JTextField jTextFieldProizvod) {
        this.jTextFieldProizvod = jTextFieldProizvod;
    }

    public JTextField getjTextFieldProizvodjac() {
        return jTextFieldProizvodjac;
    }

    public void setjTextFieldProizvodjac(JTextField jTextFieldProizvodjac) {
        this.jTextFieldProizvodjac = jTextFieldProizvodjac;
    }

    public JTextField getjTextFieldUkupnaKol() {
        return jTextFieldUkupnaKol;
    }

    /**
     * @param args the command line arguments
     */
    public void setjTextFieldUkupnaKol(JTextField jTextFieldUkupnaKol) {
        this.jTextFieldUkupnaKol = jTextFieldUkupnaKol;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JComboBox<KategorijaOpreme> jComboBoxKategorijaOpreme;
    private javax.swing.JLabel jLabelCenaPoDanu;
    private javax.swing.JLabel jLabelDostupnaKol;
    private javax.swing.JLabel jLabelKategorijaOpreme;
    private javax.swing.JLabel jLabelProizvod;
    private javax.swing.JLabel jLabelProizvodjac;
    private javax.swing.JLabel jLabelUkupnaKol;
    private javax.swing.JTextField jTextFieldCenaPoDanu;
    private javax.swing.JTextField jTextFieldDostupnaKol;
    private javax.swing.JTextField jTextFieldProizvod;
    private javax.swing.JTextField jTextFieldProizvodjac;
    private javax.swing.JTextField jTextFieldUkupnaKol;
    // End of variables declaration//GEN-END:variables
}
